// Phase 2 - 50 Deep-Dive Questions across 10 Health Areas
// Each area: 1 GOAL question (commitment) + 4 DIAGNOSTIC questions (refinement)

export const PHASE2_AREAS = [
  {
    id: 'cardiovascular',
    name: 'Cardiovascular Health',
    icon: '❤️',
    description: 'Heart, blood pressure, circulation, endurance'
  },
  {
    id: 'neurological',
    name: 'Neurological Health',
    icon: '🧠',
    description: 'Headaches, tremors, balance, nerve function'
  },
  {
    id: 'brain_cognitive',
    name: 'Brain & Cognitive',
    icon: '💡',
    description: 'Memory, focus, mental clarity, cognitive decline'
  },
  {
    id: 'fitness',
    name: 'Fitness & Strength',
    icon: '💪',
    description: 'Strength, endurance, functional fitness, energy'
  },
  {
    id: 'diet',
    name: 'Diet & Nutrition',
    icon: '🥗',
    description: 'Whole foods, intolerances, hydration, eating habits'
  },
  {
    id: 'skin',
    name: 'Skin & Face',
    icon: '✨',
    description: 'Skin condition, aging, sun exposure, skincare'
  },
  {
    id: 'sleep',
    name: 'Sleep Health',
    icon: '😴',
    description: 'Sleep hours, quality, disruptions, sleep apnea'
  },
  {
    id: 'pain',
    name: 'Pain Management',
    icon: '🛡️',
    description: 'Chronic pain, locations, severity, relief methods'
  },
  {
    id: 'digestive',
    name: 'Digestive Health',
    icon: '🫀',
    description: 'GI discomfort, symptoms, digestion, food triggers'
  },
  {
    id: 'balance',
    name: 'Balance & Dizziness',
    icon: '⚖️',
    description: 'Fall risk, dizziness, balance, mobility, stability'
  },
]

export const PHASE2_QUESTIONS = {
  cardiovascular: [
    {
      id: 'cv_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary cardiovascular goal?',
      options: [
        { text: 'Improve endurance', value: 'endurance' },
        { text: 'Lower blood pressure', value: 'lower_bp' },
        { text: 'Reduce chest symptoms', value: 'chest_symptoms' },
        { text: 'Improve recovery', value: 'recovery' },
        { text: 'General heart health', value: 'general' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'cv_stairs',
      type: 'single-select',
      question: 'Can you walk up stairs without getting short of breath?',
      options: [
        { text: 'Easily', value: 'easily', years: -1 },
        { text: 'With some effort', value: 'some_effort', years: 0 },
        { text: 'With difficulty', value: 'difficulty', years: 1 },
        { text: 'Unable', value: 'unable', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
    {
      id: 'cv_chest',
      type: 'single-select',
      question: 'How often do you experience chest discomfort or shortness of breath?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: 'Occasionally (1-2x/month)', value: 'occasionally', years: 1 },
        { text: 'Weekly', value: 'weekly', years: 2 },
        { text: 'Daily', value: 'daily', years: 3 },
      ],
      yearsImpact: '0 to +3',
    },
    {
      id: 'cv_meds',
      type: 'single-select',
      question: 'Do you take blood pressure or heart medication?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Yes (well controlled)', value: 'controlled', years: 1 },
        { text: 'Yes (not well controlled)', value: 'not_controlled', years: 2 },
        { text: 'Prefer not to say', value: 'unsure', years: 0 },
      ],
      yearsImpact: '0 to +2',
    },
    {
      id: 'cv_dizziness',
      type: 'single-select',
      question: 'How often do you feel dizzy or lightheaded when standing?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: 'Occasionally', value: 'occasionally', years: 0.5 },
        { text: 'Frequently', value: 'frequently', years: 1 },
        { text: 'Most of the time', value: 'most', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
  ],

  neurological: [
    {
      id: 'neuro_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What neurological concern matters most to you?',
      options: [
        { text: 'Manage headaches', value: 'headaches' },
        { text: 'Prevent tremors', value: 'tremors' },
        { text: 'Improve balance', value: 'balance' },
        { text: 'Better focus', value: 'focus' },
        { text: 'Other', value: 'other' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'neuro_headaches',
      type: 'single-select',
      question: 'How often do you experience headaches?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: '1-3 times/month', value: 'monthly', years: 0.5 },
        { text: '1-2 times/week', value: 'weekly', years: 1 },
        { text: '3+ times/week', value: 'frequent', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
    {
      id: 'neuro_tremors',
      type: 'single-select',
      question: 'Do you feel tremors or shakiness in your hands?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: 'Occasionally', value: 'occasionally', years: 0.5 },
        { text: 'Regularly', value: 'regularly', years: 1.5 },
        { text: 'Severe/constant', value: 'severe', years: 2 },
      ],
      yearsImpact: '0 to +2',
    },
    {
      id: 'neuro_numbness',
      type: 'single-select',
      question: 'Do you experience numbness or tingling in extremities?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Occasional', value: 'occasional', years: 0.5 },
        { text: 'Frequent', value: 'frequent', years: 0.75 },
        { text: 'Constant', value: 'constant', years: 1 },
      ],
      yearsImpact: '0 to +1',
    },
    {
      id: 'neuro_balance',
      type: 'single-select',
      question: 'How is your ability to balance (walking, standing on one leg)?',
      options: [
        { text: 'Excellent', value: 'excellent', years: -1 },
        { text: 'Good', value: 'good', years: 0 },
        { text: 'Fair', value: 'fair', years: 0.5 },
        { text: 'Poor', value: 'poor', years: 1.5 },
        { text: 'Very poor', value: 'very_poor', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
  ],

  brain_cognitive: [
    {
      id: 'brain_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary cognitive goal?',
      options: [
        { text: 'Improve memory', value: 'memory' },
        { text: 'Better focus/concentration', value: 'focus' },
        { text: 'Mental clarity', value: 'clarity' },
        { text: 'Prevent cognitive decline', value: 'decline' },
        { text: 'Other', value: 'other' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'brain_memory',
      type: 'single-select',
      question: 'How is your memory compared to 5 years ago?',
      options: [
        { text: 'Better', value: 'better', years: -0.5 },
        { text: 'Same', value: 'same', years: 0 },
        { text: 'Slightly worse', value: 'slightly', years: 0.5 },
        { text: 'Noticeably worse', value: 'noticeably', years: 1.5 },
        { text: 'Much worse', value: 'much', years: 2 },
      ],
      yearsImpact: '-0.5 to +2',
    },
    {
      id: 'brain_focus',
      type: 'single-select',
      question: 'How long can you focus on a task without distraction?',
      options: [
        { text: 'Less than 15 minutes', value: 'less15', years: 1 },
        { text: '15-45 minutes', value: '15-45', years: 0.5 },
        { text: '45-90 minutes', value: '45-90', years: 0 },
        { text: '2+ hours', value: '2plus', years: -0.5 },
      ],
      yearsImpact: '-0.5 to +1',
    },
    {
      id: 'brain_clarity',
      type: 'single-select',
      question: 'How would you rate your mental clarity and sharpness?',
      options: [
        { text: 'Very sharp', value: 'sharp', years: -0.5 },
        { text: 'Mostly clear', value: 'clear', years: 0 },
        { text: 'Often foggy', value: 'foggy', years: 1 },
        { text: 'Very foggy', value: 'very_foggy', years: 1.5 },
        { text: 'Constant brain fog', value: 'constant', years: 2 },
      ],
      yearsImpact: '-0.5 to +2',
    },
    {
      id: 'brain_family',
      type: 'single-select',
      question: 'Do you have family history of dementia or Alzheimer\'s?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Yes (parent/grandparent)', value: 'one', years: 0.75 },
        { text: 'Yes (multiple relatives)', value: 'multiple', years: 1.5 },
        { text: 'Unsure', value: 'unsure', years: 0 },
      ],
      yearsImpact: '0 to +1.5',
    },
  ],

  fitness: [
    {
      id: 'fit_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary fitness goal?',
      options: [
        { text: 'Build strength', value: 'strength' },
        { text: 'Improve endurance', value: 'endurance' },
        { text: 'Lose weight', value: 'weight' },
        { text: 'Increase energy', value: 'energy' },
        { text: 'Functional fitness', value: 'functional' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'fit_pushups',
      type: 'single-select',
      question: 'How many push-ups can you do in one set?',
      options: [
        { text: '0-5', value: '0-5', years: 2 },
        { text: '6-15', value: '6-15', years: 1 },
        { text: '16-30', value: '16-30', years: 0 },
        { text: '31-50', value: '31-50', years: -0.5 },
        { text: '50+', value: '50plus', years: -1 },
      ],
      yearsImpact: '-1 to +2',
    },
    {
      id: 'fit_intensity',
      type: 'single-select',
      question: 'What is your typical exercise intensity (when you exercise)?',
      options: [
        { text: 'Light (walking, stretching)', value: 'light', years: 2 },
        { text: 'Moderate (elevated heart rate)', value: 'moderate', years: 0.5 },
        { text: 'Vigorous (hard breathing)', value: 'vigorous', years: 0 },
        { text: 'Very intense (max effort)', value: 'intense', years: -0.5 },
        { text: 'Don\'t exercise', value: 'none', years: 1.5 },
      ],
      yearsImpact: '-0.5 to +2',
    },
    {
      id: 'fit_recovery',
      type: 'single-select',
      question: 'How long does it take to recover after exercise?',
      options: [
        { text: 'Hours (same day)', value: 'hours', years: -1 },
        { text: 'Next morning', value: 'next_morning', years: 0 },
        { text: '1-2 days', value: '1-2_days', years: 0.5 },
        { text: '3+ days', value: '3plus_days', years: 1.5 },
        { text: 'I don\'t recover well', value: 'poor', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
    {
      id: 'fit_energy',
      type: 'single-select',
      question: 'How is your energy level throughout the day?',
      options: [
        { text: 'High (consistently energetic)', value: 'high', years: -1 },
        { text: 'Moderate', value: 'moderate', years: 0 },
        { text: 'Low (frequent fatigue)', value: 'low', years: 1 },
        { text: 'Varies widely', value: 'varies', years: 0.5 },
        { text: 'Very low', value: 'very_low', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
  ],

  diet: [
    {
      id: 'diet_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary nutrition goal?',
      options: [
        { text: 'Lose weight', value: 'weight' },
        { text: 'Lower cholesterol', value: 'cholesterol' },
        { text: 'Better digestion', value: 'digestion' },
        { text: 'More energy', value: 'energy' },
        { text: 'Reduce inflammation', value: 'inflammation' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'diet_whole_foods',
      type: 'single-select',
      question: 'How consistently do you eat whole, unprocessed foods?',
      options: [
        { text: 'Most meals', value: 'most', years: -1.5 },
        { text: 'About half', value: 'half', years: 0 },
        { text: 'Occasional', value: 'occasional', years: 0.5 },
        { text: 'Rarely', value: 'rarely', years: 1.5 },
        { text: 'Never', value: 'never', years: 2.5 },
      ],
      yearsImpact: '-1.5 to +2.5',
    },
    {
      id: 'diet_intolerances',
      type: 'multi-select',
      question: 'Do you have any food intolerances or sensitivities? (Check all that apply)',
      options: [
        { text: 'None', value: 'none', years: 0 },
        { text: 'Dairy', value: 'dairy', years: 0.5 },
        { text: 'Gluten', value: 'gluten', years: 0.5 },
        { text: 'Soy', value: 'soy', years: 0.5 },
        { text: 'Nuts', value: 'nuts', years: 0.5 },
        { text: 'Corn', value: 'corn', years: 0.5 },
        { text: 'Other', value: 'other', years: 0.5 },
      ],
      yearsImpact: '0 to +1 per intolerance',
    },
    {
      id: 'diet_water',
      type: 'single-select',
      question: 'How much water do you typically drink per day?',
      options: [
        { text: 'Less than 2 cups', value: 'less2', years: 1 },
        { text: '2-4 cups', value: '2-4', years: 0.5 },
        { text: '4-8 cups', value: '4-8', years: 0 },
        { text: '8+ cups', value: '8plus', years: -0.5 },
        { text: '10+ cups', value: '10plus', years: -0.5 },
      ],
      yearsImpact: '-0.5 to +1',
    },
    {
      id: 'diet_tracking',
      type: 'single-select',
      question: 'Do you track your nutrition or follow a specific diet?',
      options: [
        { text: 'No, eat whatever', value: 'no', years: 1 },
        { text: 'Loosely aware', value: 'loose', years: 0.5 },
        { text: 'Yes, track daily', value: 'daily', years: -0.5 },
        { text: 'Yes, strict plan', value: 'strict', years: -0.5 },
        { text: 'Professional guidance', value: 'professional', years: -1 },
      ],
      yearsImpact: '-1 to +1',
    },
  ],

  skin: [
    {
      id: 'skin_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your main skin concern?',
      options: [
        { text: 'Acne', value: 'acne' },
        { text: 'Aging signs', value: 'aging' },
        { text: 'Dryness', value: 'dryness' },
        { text: 'Sensitivity', value: 'sensitivity' },
        { text: 'Discoloration', value: 'discoloration' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'skin_condition',
      type: 'single-select',
      question: 'How would you describe your skin overall?',
      options: [
        { text: 'Clear', value: 'clear', years: 0 },
        { text: 'Occasional issues', value: 'occasional', years: 0.25 },
        { text: 'Frequent issues', value: 'frequent', years: 0.5 },
        { text: 'Sensitive', value: 'sensitive', years: 0.75 },
        { text: 'Compromised barrier', value: 'compromised', years: 1 },
      ],
      yearsImpact: '0 to +1',
    },
    {
      id: 'skin_sun',
      type: 'single-select',
      question: 'How much sun exposure do you get weekly?',
      options: [
        { text: 'Less than 2 hours', value: 'less2', years: 0 },
        { text: '2-5 hours', value: '2-5', years: 0.25 },
        { text: '5-10 hours', value: '5-10', years: 0.75 },
        { text: '10+ hours', value: '10plus', years: 1 },
        { text: 'Extreme exposure', value: 'extreme', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
    {
      id: 'skin_routine',
      type: 'single-select',
      question: 'Do you follow a consistent skincare routine?',
      options: [
        { text: 'No routine', value: 'no', years: 0.5 },
        { text: 'Minimal (cleanser only)', value: 'minimal', years: 0.25 },
        { text: 'Basic (cleanser + moisturizer)', value: 'basic', years: 0 },
        { text: 'Comprehensive (multiple steps)', value: 'comprehensive', years: -0.25 },
        { text: 'Professional care', value: 'professional', years: -0.5 },
      ],
      yearsImpact: '-0.5 to +0.5',
    },
    {
      id: 'skin_changes',
      type: 'single-select',
      question: 'Have you noticed skin changes in the past year?',
      options: [
        { text: 'No changes', value: 'no', years: 0 },
        { text: 'Minor (dryness, slight sagging)', value: 'minor', years: 0.25 },
        { text: 'Moderate (visible lines, tone changes)', value: 'moderate', years: 0.5 },
        { text: 'Significant', value: 'significant', years: 0.75 },
        { text: 'Dramatic', value: 'dramatic', years: 1 },
      ],
      yearsImpact: '0 to +1',
    },
  ],

  sleep: [
    {
      id: 'sleep_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary sleep goal?',
      options: [
        { text: 'Sleep more hours', value: 'hours' },
        { text: 'Better quality', value: 'quality' },
        { text: 'Stop waking at night', value: 'waking' },
        { text: 'Fall asleep faster', value: 'latency' },
        { text: 'Rule out sleep apnea', value: 'apnea' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'sleep_disruptions',
      type: 'multi-select',
      question: 'What disrupts your sleep? (Check all that apply)',
      options: [
        { text: 'Nothing', value: 'nothing', years: 0 },
        { text: 'Stress/racing mind', value: 'stress', years: 0.25 },
        { text: 'Pain', value: 'pain', years: 0.25 },
        { text: 'Bathroom trips', value: 'bathroom', years: 0.25 },
        { text: 'Noise', value: 'noise', years: 0.25 },
        { text: 'Partner', value: 'partner', years: 0.25 },
        { text: 'Sleep apnea', value: 'apnea', years: 1.5 },
        { text: 'Caffeine', value: 'caffeine', years: 0.25 },
        { text: 'Schedule', value: 'schedule', years: 0.25 },
      ],
      yearsImpact: '0 to +2 cumulative',
    },
    {
      id: 'sleep_rested',
      type: 'single-select',
      question: 'How rested do you feel when you wake up?',
      options: [
        { text: 'Very rested', value: 'very', years: -1 },
        { text: 'Mostly rested', value: 'mostly', years: 0 },
        { text: 'Somewhat rested', value: 'somewhat', years: 0.5 },
        { text: 'Barely rested', value: 'barely', years: 1.5 },
        { text: 'Exhausted', value: 'exhausted', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
    {
      id: 'sleep_apnea',
      type: 'single-select',
      question: 'Have you been evaluated for sleep apnea?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Suspected but not tested', value: 'suspected', years: 1 },
        { text: 'Tested - negative', value: 'negative', years: 0 },
        { text: 'Yes - untreated', value: 'untreated', years: 3 },
        { text: 'Yes - treated (CPAP/other)', value: 'treated', years: -0.5 },
      ],
      yearsImpact: '-0.5 to +3',
    },
    {
      id: 'sleep_preference',
      type: 'single-select',
      question: 'When do you naturally prefer to sleep?',
      options: [
        { text: 'Early (9-10pm)', value: 'early', years: 0 },
        { text: 'Normal (10-11pm)', value: 'normal', years: 0 },
        { text: 'Late (11pm+)', value: 'late', years: 0.25 },
        { text: 'Varies widely', value: 'varies', years: 0.25 },
        { text: 'I\'m a shift worker', value: 'shift', years: 0.5 },
      ],
      yearsImpact: '0 to +0.5',
    },
  ],

  pain: [
    {
      id: 'pain_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary pain concern?',
      options: [
        { text: 'Manage chronic pain', value: 'manage' },
        { text: 'Reduce inflammation', value: 'inflammation' },
        { text: 'Improve mobility', value: 'mobility' },
        { text: 'Reduce medication', value: 'medication' },
        { text: 'Prevent worsening', value: 'prevent' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'pain_severity',
      type: 'single-select',
      question: 'Do you experience chronic pain?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Occasional', value: 'occasional', years: 0.5 },
        { text: 'Moderate (daily but manageable)', value: 'moderate', years: 1 },
        { text: 'Severe (daily, limiting)', value: 'severe', years: 1.5 },
        { text: 'Debilitating', value: 'debilitating', years: 2 },
      ],
      yearsImpact: '0 to +2',
    },
    {
      id: 'pain_locations',
      type: 'multi-select',
      question: 'Where is your pain located? (Check all that apply)',
      options: [
        { text: 'No pain', value: 'none', years: 0 },
        { text: 'Head', value: 'head', years: 0.25 },
        { text: 'Neck', value: 'neck', years: 0.25 },
        { text: 'Shoulders', value: 'shoulders', years: 0.25 },
        { text: 'Back', value: 'back', years: 0.25 },
        { text: 'Lower back', value: 'lower_back', years: 0.25 },
        { text: 'Hips', value: 'hips', years: 0.25 },
        { text: 'Knees', value: 'knees', years: 0.25 },
        { text: 'Ankles', value: 'ankles', years: 0.25 },
        { text: 'Other', value: 'other', years: 0.25 },
      ],
      yearsImpact: '0 to +1 per location',
    },
    {
      id: 'pain_duration',
      type: 'single-select',
      question: 'How long have you had this pain?',
      options: [
        { text: 'Less than 1 month', value: 'less1m', years: 0.25 },
        { text: '1-6 months', value: '1-6m', years: 0.75 },
        { text: '6-12 months', value: '6-12m', years: 1 },
        { text: '1-3 years', value: '1-3y', years: 1.25 },
        { text: '3+ years', value: '3plus', years: 1.5 },
      ],
      yearsImpact: '0.25 to +1.5',
    },
    {
      id: 'pain_relief',
      type: 'multi-select',
      question: 'What helps your pain most? (Check all that apply)',
      options: [
        { text: 'Rest', value: 'rest', years: 0 },
        { text: 'Movement/stretching', value: 'movement', years: 0 },
        { text: 'Heat/cold', value: 'heat_cold', years: 0 },
        { text: 'Medication', value: 'medication', years: 0 },
        { text: 'Therapy (PT, massage)', value: 'therapy', years: 0 },
        { text: 'Nothing', value: 'nothing', years: 1 },
        { text: 'Unsure', value: 'unsure', years: 0.5 },
      ],
      yearsImpact: 'Varies by method',
    },
  ],

  digestive: [
    {
      id: 'dig_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What digestive issue concerns you most?',
      options: [
        { text: 'Bloating', value: 'bloating' },
        { text: 'Constipation', value: 'constipation' },
        { text: 'Diarrhea', value: 'diarrhea' },
        { text: 'Acid reflux', value: 'reflux' },
        { text: 'General discomfort', value: 'general' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'dig_frequency',
      type: 'single-select',
      question: 'How often do you experience GI discomfort?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: 'Occasionally (1-2x/month)', value: 'occasional', years: 0.5 },
        { text: 'Weekly', value: 'weekly', years: 0.75 },
        { text: 'Several times/week', value: 'several', years: 1 },
        { text: 'Daily', value: 'daily', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
    {
      id: 'dig_symptoms',
      type: 'multi-select',
      question: 'What GI symptoms do you experience? (Check all that apply)',
      options: [
        { text: 'None', value: 'none', years: 0 },
        { text: 'Bloating', value: 'bloating', years: 0.25 },
        { text: 'Gas', value: 'gas', years: 0.25 },
        { text: 'Cramping', value: 'cramping', years: 0.25 },
        { text: 'Constipation', value: 'constipation', years: 0.25 },
        { text: 'Diarrhea', value: 'diarrhea', years: 0.25 },
        { text: 'Acid reflux', value: 'reflux', years: 0.25 },
        { text: 'Nausea', value: 'nausea', years: 0.25 },
      ],
      yearsImpact: '0 to +1 cumulative',
    },
    {
      id: 'dig_appetite',
      type: 'single-select',
      question: 'How is your appetite?',
      options: [
        { text: 'Normal', value: 'normal', years: 0 },
        { text: 'Decreased (not hungry)', value: 'decreased', years: 0.5 },
        { text: 'Increased (always hungry)', value: 'increased', years: 0.5 },
        { text: 'Unpredictable', value: 'unpredictable', years: 0.5 },
        { text: 'Nausea prevents eating', value: 'nausea', years: 1 },
      ],
      yearsImpact: '0 to +1',
    },
    {
      id: 'dig_triggers',
      type: 'single-select',
      question: 'Do certain foods trigger your GI issues?',
      options: [
        { text: 'No specific triggers', value: 'no', years: 0 },
        { text: 'A few foods', value: 'few', years: 0.5 },
        { text: 'Many foods', value: 'many', years: 1 },
        { text: 'Gluten/dairy/sugar', value: 'common', years: 0.75 },
        { text: 'Always having reactions', value: 'always', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
  ],

  balance: [
    {
      id: 'bal_goal',
      type: 'single-select',
      isGoal: true,
      question: 'What is your primary balance/dizziness concern?',
      options: [
        { text: 'Prevent falls', value: 'falls' },
        { text: 'Reduce dizziness', value: 'dizziness' },
        { text: 'Improve stability', value: 'stability' },
        { text: 'Regain confidence', value: 'confidence' },
        { text: 'Other', value: 'other' },
      ],
      yearsImpact: 'N/A',
    },
    {
      id: 'bal_falls',
      type: 'single-select',
      question: 'Have you had falls or near-falls in the past year?',
      options: [
        { text: 'None', value: 'none', years: 0 },
        { text: '1 incident', value: 'one', years: 0.5 },
        { text: '2-3 incidents', value: 'few', years: 1 },
        { text: 'Multiple incidents', value: 'multiple', years: 1.5 },
        { text: 'Frequent', value: 'frequent', years: 2 },
      ],
      yearsImpact: '0 to +2',
    },
    {
      id: 'bal_dizziness',
      type: 'single-select',
      question: 'Do you experience dizziness or vertigo?',
      options: [
        { text: 'Never', value: 'never', years: 0 },
        { text: 'When standing suddenly', value: 'standing', years: 0.5 },
        { text: 'With position changes', value: 'position', years: 0.75 },
        { text: 'Frequently', value: 'frequently', years: 1 },
        { text: 'Constant', value: 'constant', years: 1.5 },
      ],
      yearsImpact: '0 to +1.5',
    },
    {
      id: 'bal_confidence',
      type: 'single-select',
      question: 'How confident are you in your balance?',
      options: [
        { text: 'Very confident', value: 'very', years: -1 },
        { text: 'Mostly confident', value: 'mostly', years: 0 },
        { text: 'Somewhat confident', value: 'somewhat', years: 0.75 },
        { text: 'Not confident', value: 'not', years: 1.5 },
        { text: 'Very unstable', value: 'unstable', years: 2 },
      ],
      yearsImpact: '-1 to +2',
    },
    {
      id: 'bal_support',
      type: 'single-select',
      question: 'Do you need support when walking (cane, walker, holding onto things)?',
      options: [
        { text: 'No', value: 'no', years: 0 },
        { text: 'Sometimes in certain situations', value: 'sometimes', years: 0.75 },
        { text: 'Often', value: 'often', years: 1.5 },
        { text: 'Always', value: 'always', years: 2 },
        { text: 'Unable to walk without assistance', value: 'unable', years: 2.5 },
      ],
      yearsImpact: '0 to +2.5',
    },
  ],
}
